#!/bin/sh

# This TOP variable hack is taken from try's test suite
JINMORI_TOP="${JINMORI_TOP:-$(git rev-parse --show-toplevel --show-superproject-working-tree 2>/dev/null || echo "${0%/*}")}"
JINMORI="$JINMORI_TOP/build/jinmori.dbg"
TESTS="$JINMORI_TOP/test/integration"
export JINMORI

if [ -z "$TRY" ]; then
	echo "Please set \$TRY to the path of your try script" >&2
	exit 1
fi

for test in "$TESTS/success/*"; do
	if ! "$TRY" -n "$test"; then
		echo "$test" >&2
		exit 1
	fi
done
