name: Build assets

on:
  push:
    tags: 
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mlton          

      - name: Build
        run: yes | bash bootstrap.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/jinmori

