name: Main workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Allow unprivileged user namespaces (for Ubuntu 24.04)
        run: |
          sudo sysctl kernel.apparmor_restrict_unprivileged_userns=0

      - name: Install dependencies
        run: |
          curl -L -o /tmp/mlton-2024.tgz https://github.com/MLton/mlton/releases/download/on-20241230-release/mlton-20241230-1.amd64-linux.ubuntu-24.04_glibc2.39.tgz
          tar -xzf /tmp/mlton-2024.tgz -C "$HOME"
          sudo make -C "$HOME/mlton-20241230-1.amd64-linux.ubuntu-24.04_glibc2.39" install
          mlton

          sudo apt-get update
          sudo apt-get install attr 
          curl -L -o try https://raw.githubusercontent.com/binpash/try/main/try
          chmod +x try
          ./try --version

      - name: Build binaries
        run: |
          mkdir -p bin
          make all

      - name: Run tests
        shell: sh {0}
        run: |
          make test
          tests/end2end/runner
